import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import FallingItems from "./components/ui/FallingItems";
import { Great_Vibes, Playfair_Display } from "next/font/google";
import BackgroundMusic from "./components/ui/BackgroundMusic";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-great-vibes",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
  className={`${geistSans.variable} ${geistMono.variable} ${greatVibes.variable} ${playfair.variable} antialiased`}
      >
       
        <BackgroundMusic />
        <Navbar />
        <FallingItems
  leafCount={10}
  flowerCount={6}
  minSize={15}
  maxSize={40}
  minDuration={13}
  maxDuration={22}
/>
        {children}
          <Footer />
        
      </body>
    </html>
  );
}
